# Generated by Django 4.1.3 on 2023-01-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_delays", models.TextField()),
                ("stop_delays", models.TextField()),
                ("floors_traversed", models.IntegerField()),
                ("log_dict", models.TextField()),
            ],
        ),
    ]
