# Generated by Django 4.1.3 on 2023-02-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevatorSim", "0002_simulationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="simulationrequest",
            name="rider_list",
            field=models.TextField(),
        ),
    ]
