# Generated by Django 4.1.3 on 2023-02-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevatorSim", "0003_alter_simulation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="TIME_STEP",
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simulation",
            name="elevate_type",
            field=models.TextField(default="elevate"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simulation",
            name="num_elevators",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simulation",
            name="rider_list",
            field=models.TextField(default="test;1;2;0"),
            preserve_default=False,
        ),
    ]
