# Generated by Django 4.1.3 on 2023-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevatorSim", "0004_simulation_time_step_simulation_elevate_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrequest",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default="2023-03-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simulationrequest",
            name="floors_traversed",
            field=models.IntegerField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="simulationrequest",
            name="log_dict",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="simulationrequest",
            name="step_delays",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="simulationrequest",
            name="stop_delays",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="simulationrequest",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
