# Generated by Django 4.1.3 on 2023-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevatorSim", "0005_simulationrequest_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationrequest",
            name="floors_traversed",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
