# Generated by Django 4.1.3 on 2023-03-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevatorSim", "0006_alter_simulationrequest_floors_traversed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationrequest",
            name="floors_traversed",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
