# Generated by Django 4.1.3 on 2023-03-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevatorSim", "0007_alter_simulationrequest_floors_traversed"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrequest",
            name="graph_id",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
